import { pgTable, text, boolean, integer, jsonb } from 'drizzle-orm/pg-core';

export const shortageBookings = pgTable('shortage_bookings', {
  id: text('id').primaryKey(),
  ticketNumber: text('ticket_number').notNull(),
  partCode: text('part_code').notNull(),
  partName: text('part_name').notNull(),
  model: text('model'),
  partsList: jsonb('parts_list'),
  bookingDate: text('booking_date').notNull(),
  requestedDate: text('requested_date'),
  customerName: text('customer_name').notNull(),
  customerPhone: text('customer_phone').notNull(),
  status: text('status').notNull(),
  location: text('location'),
  stockedInDate: text('stocked_in_date'),
  calledCustomerDate: text('called_customer_date'),
  callSubStatus: text('call_sub_status'),
  appointmentDate: text('appointment_date'),
  callNote: text('call_note'),
  callLogs: jsonb('call_logs'),
  customerArrivedDate: text('customer_arrived_date'),
  technicianName: text('technician_name'),
  note: text('note'),
  cancelRequested: boolean('cancel_requested').default(false),
  cancelReason: text('cancel_reason'),
  cancelRequestedBy: text('cancel_requested_by'),
  cancelRequestedAt: text('cancel_requested_at'),
  customerKeepsPart: boolean('customer_keeps_part').default(false),
  isCustomerCallHold: boolean('is_customer_call_hold').default(false),
  isCompletedWithoutRepair: boolean('is_completed_without_repair').default(false),
  closureReason: text('closure_reason'),
  closureNote: text('closure_note'),
  closureBy: text('closure_by'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  history: jsonb('history'),
  createdBy: text('created_by'),
  createdByUid: text('created_by_uid'),
  creatorTechnician: text('creator_technician'),
});

export const labelCatalog = pgTable('label_catalog', {
  id: text('id').primaryKey(),
  code: text('code').notNull(),
  name: text('name').notNull(),
  model: text('model'),
  category: text('category'),
  quantity: integer('quantity').default(1),
  price: text('price'),
  location: text('location'),
  date: text('date'),
  note: text('note'),
});

export const activityLogs = pgTable('activity_logs', {
  id: text('id').primaryKey(),
  action: text('action').notNull(),
  ticketNumber: text('ticket_number'),
  userName: text('user_name'),
  timestamp: text('timestamp').notNull(),
  details: text('details'),
});

export const appStats = pgTable('app_stats', {
  key: text('key').primaryKey(),
  value: jsonb('value'),
});

export const appUsers = pgTable('app_users', {
  uid: text('uid').primaryKey(),
  username: text('username').notNull(),
  password: text('password'),
  displayName: text('display_name'),
  role: text('role').notNull().default('staff'),
  status: text('status').notNull().default('pending'),
  online: boolean('online').default(false),
  lastActive: text('last_active'),
  approvedBy: text('approved_by'),
  approvedAt: text('approved_at'),
  createdAt: text('created_at'),
});

export const technicians = pgTable('technicians', {
  id: text('id').primaryKey(),
  techId: text('tech_id').notNull(),
  name: text('name').notNull(),
  phone: text('phone'),
  department: text('department'),
  status: text('status').notNull().default('active'),
  requestedBy: text('requested_by'),
  requestedAt: text('requested_at'),
  approvedBy: text('approved_by'),
  approvedAt: text('approved_at'),
  note: text('note'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const deviceIotBookings = pgTable('device_iot_bookings', {
  id: text('id').primaryKey(),
  ticketNumber: text('ticket_number').notNull(),
  customerName: text('customer_name').notNull(),
  customerPhone: text('customer_phone').notNull(),
  deviceModel: text('device_model').notNull(),
  deviceName: text('device_name').notNull(),
  skuCode: text('sku_code'),
  imeiOrIot: text('imei_or_iot').notNull(),
  deviceCategory: text('device_category').default('phone'),
  flowType: text('flow_type').notNull().default('request_device'),
  status: text('status').notNull(),
  bookingDate: text('booking_date').notNull(),
  requestedDate: text('requested_date'),
  stockedInDate: text('stocked_in_date'),
  location: text('location'),
  hasDeposit: boolean('has_deposit').default(false),
  depositType: text('deposit_type'),
  depositAmount: text('deposit_amount'),
  borrowedDate: text('borrowed_date'),
  returnedDate: text('returned_date'),
  loanHandoverBy: text('loan_handover_by'),
  loanReceivedBy: text('loan_received_by'),
  loanCondition: text('loan_condition'),
  loanAccessories: text('loan_accessories'),
  calledCustomerDate: text('called_customer_date'),
  callSubStatus: text('call_sub_status'),
  appointmentDate: text('appointment_date'),
  callNote: text('call_note'),
  callLogs: jsonb('call_logs'),
  customerArrivedDate: text('customer_arrived_date'),
  technicianName: text('technician_name'),
  note: text('note'),
  isCompletedWithoutExchange: boolean('is_completed_without_exchange').default(false),
  closureReason: text('closure_reason'),
  closureNote: text('closure_note'),
  closureBy: text('closure_by'),
  cancelRequested: boolean('cancel_requested').default(false),
  cancelReason: text('cancel_reason'),
  cancelRequestedBy: text('cancel_requested_by'),
  cancelRequestedAt: text('cancel_requested_at'),
  history: jsonb('history'),
  createdBy: text('created_by'),
  createdByUid: text('created_by_uid'),
  creatorTechnician: text('creator_technician'),
  warrantyCenterName: text('warranty_center_name'),
  warrantyCenterPhone: text('warranty_center_phone'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

